name: Test

on:
  push:
  pull_request:
    types: [opened, synchronize]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
      fail-fast: true

    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Build the databases
        run: docker-compose up -d
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install -E sqlalchemy -E mysqlclient
      - name: Run tests
        run: poetry run test
      - name: Upload coverage
        uses: codecov/codecov-action@v1
